[main]
font=JetBrainsMonoNerdFont-Medium:size=12

[colors]
alpha=0.80

# Base
foreground=E6DFD5
background=2B2623

# Cores normais
regular0=2B2623  # black
regular1=C25A5A  # red
regular2=8EB85F  # green
regular3=D9A441  # yellow
regular4=6D8EBE  # blue
regular5=B07AA1  # magenta
regular6=6BB6B2  # cyan
regular7=D6CFC7  # white

# Cores brilhantes
bright0=605953  # bright black (gray)
bright1=E37979  # bright red
bright2=A7D879  # bright green
bright3=F0C25E  # bright yellow
bright4=86A7D8  # bright blue
bright5=C998C1  # bright magenta
bright6=85D2CE  # bright cyan
bright7=F2ECE4  # bright white

