font_family JetBrainsMonoNerdFont-Medium
font_size 12
# background_opacity 1

foreground  #cdd6f4
background  #1e1e2e

selection_foreground #1e1e2e
selection_background #f5e0dc

cursor #f5e0dc
cursor_text_color #1e1e2e

# Preto
color0  #45475a
color8  #585b70

# Vermelho
color1  #f38ba8
color9  #f38ba8

# Verde
color2  #a6e3a1
color10 #a6e3a1

# Amarelo
color3  #f9e2af
color11 #f9e2af