# Appearance options
height=500
width=500
layer=overlay
xoffset=0
yoffset=0

# General Wofi options
mode=drun
allow_images=true
hide_scroll=true
insensitive=true
show_all=true
prompt=Search: 

# Mode-specific options
run-always_parse_args=true
run-term=foot