# i3 config file (v4)
# Please see https://i3wm.org/docs/userguide.html for a complete reference!


# Configurações padrão
#####################################
set $mod Mod4
set $terminal "mate-terminal"
set $app_launcher "rofi -show drun -show-icons"
set $file_manager "caja"

font pango:Ubuntu Bold 9
default_border pixel 1
default_floating_border pixel 1
gaps inner 5

# Cores da janela
# class                   border    backgr.   text      indicator   child_border
client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff

# Autostart de componentes úteis do mate
#####################################

# Compositor e plano de fundo
exec --no-startup-id picom


# Configurações de janelas
#####################################
for_window [class="Pavucontrol"] floating enable, resize set 800 600, move position center
for_window [class="Blueman-manager"] floating enable, resize set 800 600, move position center
for_window [class="Alarm-clock-applet"] floating enable

# Mate
for_window [window_type="dialog"] floating enable
for_window [class="Mate-volume-control"] floating enable
for_window [class="Nm-connection-editor"] floating enable


# Teclas de atalho
#####################################

# recarregar o arquivo de configuração
bindsym $mod+Shift+c reload

# reiniciar o i3
bindsym $mod+Shift+r restart

# desligar o computador
bindsym $mod+Shift+q exec --no-startup-id "mate-session-save --shutdown-dialog"

bindsym $mod+Return exec $terminal
bindsym $mod+d exec $app_launcher
bindsym $mod+f exec $file_manager

# fechar a janela selecionada
bindsym $mod+q kill

# mudar o foco da janela
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# mover a janela selecionada
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+Shift+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
# bindsym $mod+s layout stacking
# bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar

# Minimizar / maximizar janelas
bindsym $mod+Shift+m move scratchpad
bindsym $mod+m scratchpad show