separator=true
separator_block_width=10

# Data e Hora
[date]
align=center
command=~/.local/bin/i3datetime
interval=60

# Ethernet / IP
[ethernet]
command=ip route get 1 | awk '{print "IP: " $7; exit}'
interval=5
color=#00ff00

# CPU
[cpu]
command=~/.local/bin/i3cpu.py
interval=1
markup=pango

# RAM
# [memory]
# full_text=RAM
# command=free -m | awk '/Mem:/ { printf "RAM: %d%%", $3*100/$2 }'
# interval=5
# label=

# Volume
[vol]
command=~/.local/bin/i3vol
interval=1
label=

# Microfone
[mic]
command=~/.local/bin/i3mic
interval=1
label=
