separator=true
separator_block_width=10

# Data e Hora
[date]
command=~/.local/bin/i3datetime.py
interval=60
color=#ccc

# CPU
[cpu]
command=~/.local/bin/i3cpu.py
interval=1
markup=pango

# RAM
[memory]
command=~/.local/bin/i3mem.py
interval=1
markup=pango

# Volume
[vol]
command=~/.local/bin/i3vol.py
interval=1
color=#ccc

# Microfone
[mic]
command=~/.local/bin/i3mic.py
interval=1
color=#ccc
