separator=true
separator_block_width=10

# Data e Hora
[date]
align=center
command=~/.local/bin/i3datetime
interval=60

# CPU
[cpu]
command=~/.local/bin/i3cpu.py
interval=1
markup=pango

# RAM
[memory]
command=~/.local/bin/i3mem.py
interval=1
markup=pango

# Volume
[vol]
command=~/.local/bin/i3vol
interval=1
label=

# Microfone
[mic]
command=~/.local/bin/i3mic
interval=1
label=
